#!/usr/bin/with-contenv bash

# display time in logging helper #
# echo "$(format_date) [INFO] etc etc"
# echo "$(format_date) [WARNING] etc etc"
format_date() {
  # echo is not needed
  date "+%Y-%m-%d %H:%M:%S"
}

if [ ! -d "/config/www/spotweb" ]; then
	cd /config/www
	git clone ${giturl}
	chown -R abc:abc /config/www/spotweb
 else
	echo "$(format_date) [INFO] Spotweb folder found ! to manually update spotweb. Remove folder: [ /config/www/spotweb ] and restart container"
fi

if [ ! -d "/config/spotweb-save" ]; then
	cd /config
	mkdir /config/spotweb-save
fi

#checks to see is spotweb setup is complete and incase of new container, restore saved setings
if [ ! -f /config/www/spotweb/dbsettings.inc.php ]; then
	echo .
	echo "$(format_date) [WARNING] dbsettings.inc.php not found please run Spotweb setup en restart container: https://thiscontainer/spotweb"
	echo "After setup is completed please restart container."
	echo .
 else 
	echo "$(format_date) [INFO] dbsettings.inc.php found spotweb is installed"
	cp /config/www/spotweb/dbsettings.inc.php /config/spotweb-save/dbsettings.inc.php
fi

if [ ! -f /config/spotweb-save/dbsettings.inc.php ] ; then
	echo .
	echo "$(format_date) [WARNING] Saved dbsettings.inc.php not found please run Spotweb setup en restart container: https://thiscontainer/spotweb"
	echo "After setup is completed please restart container."
	echo .
 else 
	echo "$(format_date) [INFO] Saved dbsettings.inc.php found restoring settings.... Please restart container if you manually copy the dbsettings.inc.php file"
	cp /config/spotweb-save/dbsettings.inc.php /config/www/spotweb/dbsettings.inc.php
fi

# check if custom cronjob exists if not create one.
if [ ! -f /config/spotweb-save/abc ] ; then
	touch /config/spotweb-save/customcronjob
	echo "# min   hour    day     month   weekday command" > /config/spotweb-save/abc
	echo "0	*	*	*	*	php /config/www/spotweb/retrieve.php > /dev/null" >> /config/spotweb-save/abc
 else 
	echo "$(format_date) [INFO] Saved customcronjob found !"
	#cp /config/www/spotweb-save/abc /etc/crontabs
fi

#check if folder for custom startup script is found, if not create one. We need an cronjob to update our spots
if [ ! -f "/config/custom-cont-init.d/addcustomcronjob" ]; then
	mkdir /config/custom-cont-init.d
	touch /config/custom-cont-init.d/addcustomcronjob
	#chmod +x /config/custom-cont-init.d/cron_retrieve-spots
	echo "#!/bin/bash" > /config/custom-cont-init.d/addcustomcronjob
	echo " " >> /config/custom-cont-init.d/addcustomcronjob
	echo "cp /config/spotweb-save/abc /etc/crontabs" >> /config/custom-cont-init.d/addcustomcronjob
	echo "chmod -R 600 /etc/crontabs" >> /config/custom-cont-init.d/addcustomcronjob
 else
	echo "$(format_date) [INFO] addcustomcronjob found ! this is a good thing"
fi

# upgrade the db
if [ ! -f "/config/www/spotweb/upgrade-db.php" ]; then
	echo "$(format_date) [INFO] upgrade-db.php not found, no upgrade needed..."
else
	echo "$(format_date) [INFO] upgrade-db.php found.. performing upgrade. If this fails and your dont have a backup of your sql spotweb db you may be fuc..d"
	s6-setuidgid abc php /config/www/spotweb/bin/upgrade-db.php
	sleep 3
	rm -rf /config/www/spotweb/bin/upgrade-db.php.old
	mv /config/www/spotweb/bin/upgrade-db.php /config/www/spotweb/bin/upgrade-db.php.old
fi
